### ISSUE TITLE
缺少 .env文件

### ISSUE THREAD

**Issue by SeongBrave** [vellengs/nestx#27]
您好，能否提供一份测试的.env文件呢，现在跑步起来啊

**Comment by vellengs** [comment]
PORT=5400
NODE_ENV=test
API_URL=https://localhost/
MONGODB_URI_PRODUCTION=mongodb://localhost/nestx-server-pro
MONGODB_URI_TEST=mongodb://localhost/nestx-server-test
MONGODB_URI_DEV=mongodb://localhost/nestx-server-dev
SESSION_SECRET=ADS13DI999999999999888
 
JWT_SECRET_KEY=HSSB33333333333333333333
JWT_EXPIRE_IN=1h
JWT_ALGORITHM=HS512
MULTER_DEST=./uploads

**Comment by vellengs** [comment]
你可以采用 .env.example 重命名下就可以的

**Comment by SeongBrave** [comment]
@vellengs 
🤝 可以了，多谢啊，学习下

**Comment by vellengs** [comment]
👌，有问题欢迎反馈 和 PR.
