### ISSUE TITLE
您好，线上的用户可以给出两个吗？我想看一下权限管理的功能

### ISSUE THREAD

**Issue by 1101916341** [vellengs/nestx#44]
您好，线上的用户可以给出两个吗？我想看一下权限管理的功能，还有server的配置必须是db菲关系型数据库吗?我这边连接时总是说ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)错误，您看下是不是数据库的配置信息有问题啊

**Comment by vellengs** [comment]
文档上有账户和密码，请仔细看下文档介绍。 
------------------
Best Regards,
Viking

QQ:614082, Cell-phone:13063090590, Email:Vellengs@qq.com


 




------------------ Original ------------------

**Comment by 1101916341** [comment]
我仔细看过文档了，您给的文档中只有一个admin账号和密码，而且，我在文档中也没有看到您介绍关于数据库方面的链接和类型以及使用方式啊

**Comment by vellengs** [comment]
数据库的用的是 Mongodb 你可以自行了解下相关的知识。
